name: learn-github-actions
on: [push]
jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download source
        run: ./pack.sh download

      - name: Patch files
        run: ./pack.sh patch

      - name: Rename out.mrpack
        run: mv out.mrpack not-so-simply-optimized.mrpack

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: not-so-simply-optimized.mrpack
